# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Medium Post copy
        uses: daiwa233/post-medium-action@v1.3.0
        with: 
          app_id: ${{ secrets.MEDIUM_APP_ID }}
          app_secret: ${{ secrets.MEDIUM_APP_SECRET }}
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}

